version: '3.7'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php-fpm
      - php-cli
      - database
      - redis
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www
      - ./docker/php-config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      DB_PORT: "5432"
      DB_HOST: "database"
      REDIS_PORT: "6379"
      REDIS_HOST: "redis"
      PHP_IDE_CONFIG: "serverName=docker"
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
      - ./docker/php-config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      DB_PORT: "5432"
      DB_HOST: "database"
      REDIS_PORT: "6379"
      REDIS_HOST: "redis"
      PHP_IDE_CONFIG: "serverName=docker"
    tty: true
  database:
    image: postgres:11-alpine
    volumes:
      - ./docker/volumes/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports:
      - "55432:5432"
  redis:
    image: redis:3.0
