version: '3.7'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php-fpm
      - php-cli
      - database
      - redis
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm.docker
    volumes:
      - ./:/var/www

    environment:
      DB_PORT: "5432"
      DB_HOST: "database"
      REDIS_PORT: "6379"
      REDIS_HOST: "redis"
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_CONFIG: "remote_port=9000 remote_host=172.17.0.1 remote_enable=1"
  php-cli:
    build:
      context: ./
      dockerfile: docker/php-cli.docker
    volumes:
      - ./:/var/www
    env_file:
      - docker-compose.env
    environment:
      DB_PORT: "5432"
      DB_HOST: "database"
      REDIS_PORT: "6379"
      REDIS_HOST: "redis"
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_CONFIG: "remote_port=9000 remote_host=172.17.0.1 remote_enable=1"
    tty: true
  database:
    image: postgres:11-alpine
    volumes:
      - ./docker/volumes/pgsql:/var/lib/pgsql
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports:
      - "55432:5432"
  redis:
    image: redis:3.0
