version: '3.7'

services:
  database:
    ports:
      - "55432:5432"
  redis:
    ports:
      - "63794:6379"
  php-fpm:
    expose:
      - "9000"
  nginx:
    ports:
      - "4445:443"
      - "8384:80"

